### ISSUE TITLE
Language is not loading

### ISSUE THREAD

**Issue by wasiqaftab** [nnjeim/world#10]
**Describe the bug**
Please check the issue. i can see the language in it

**To Reproduce**

just do a call to countries database

https://jmp.sh/bJLukcG

**Expected behavior**
Need to see country name

**Screenshots**

[If applicable, add screenshots to help explain your problem.](https://jmp.sh/bJLukcG)

**Comment by nnjeim** [comment]
@wasiqaftab Hi, thank you for reporting this. Can you please tell me how are you using the package? did you fork the repo or did you install the package in composer? did you publish php artisan vendor:publish --tag=world
from the video you attached it shows that it is not being able to resolve the world tag.

**Comment by wasiqaftab** [comment]
HI

Thanks for your quick response. Yes i publish the tag it woked with when i
choose local as per your documentation but not without that. so i assume i
need to configure something globally. Sorry which i dont understand as its
a default laravel installation

**Comment by nnjeim** [comment]
Np thank u.
