### ISSUE TITLE
Laravel 11: After installation package app read translations from resources/lang instead /lang

### ISSUE THREAD

**Issue by stefanrakicfaxi** [nnjeim/world#100]
I have an issue because package override my lang directory:
This is example of fix from another package:
public function boot()
    {
        $configPath = __DIR__.'/../../config/config.php';
        $configKey = 'localization-js';

        // Determines Laravel major version.
        $app = $this->app;
        $laravelMajorVersion = (int) $app::VERSION;

        // Publishes Laravel-JS-Localization package files and merge user and
        // package configurations.
        if ($laravelMajorVersion === 4) {
            $config = $this->app['config']->get($configKey, []);
            $this->app['config']->set($configKey, array_merge(require $configPath, $config));
        } elseif ($laravelMajorVersion >= 5) {
            $this->publishes([
                $configPath => config_path("$configKey.php"),
            ]);
            $this->mergeConfigFrom(
                $configPath, $configKey
            );
        }
    }

**Comment by nnjeim** [comment]
@stefanrakicfaxi thank you for you input. would you be interested to submit a PR with the proposed modification?

**Comment by nnjeim** [comment]
@stefanrakicfaxi 
when publishing the resources of the package the files are under 
/resources/lang/vendor/world
what is the issue in your case with this?

**Comment by alqabali** [comment]
@nnjeim in the laravel 11 the translation/language files should be in the root lang folder not resources/lang
