### ISSUE TITLE
Stuck at 40%, I see some countries are not seeded.

### ISSUE THREAD

**Issue by ahaneef29** [nnjeim/world#12]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Terminal'
2. Click on 'Run db:seed'
3. After waiting for 2 minutes
4. See error 'Stuck at 40%, I see some countries are not seeded.'

 Seeding start

 101/250 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  40%

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. MacBook]
 - OS: [e.g. MacOS Monterey]
 - Terminal [e.g. iTerm2]
 - Version [e.g. laravel 9]

**Additional context**
I tried truncating tables, Still no luck.

**Comment by nnjeim** [comment]
@ahaneef29 
Seeding normally takes 10 to 15min. Previously some users had issues with limited resources. try to increase the memory allocated for php in php.ini. If you are upgrading to the latest version, It is advisable to drop the tables and re-run php artisan migrate before seeding.

**Comment by ahaneef29** [comment]
I increased PHP memory_limit from 128M to 512M.. Still no luck.

**Comment by nnjeim** [comment]
Can please check in the logs if you have errors? if yes please share them

**Comment by ahaneef29** [comment]
Issue resolved after increasing the php memory to 2048M.
