### ISSUE TITLE
Contribute to the project

### ISSUE THREAD

**Issue by robertosanval** [nnjeim/world#22]
I want to contribute to the project. I've some implementations that I want to share.

First of all, the origin of the data, I think that you get the data from https://www.geonames.org/, is correct?

I've some projects where I use geonames, I know its database structure very well.

I'd like to add to your world project more admin levels, including more villages, not only cities.

I also have support for coordinates and geospatial searches, nearest cities from x for example.

Are you interested in these features?

**Comment by nnjeim** [comment]
@robertosanval Hi thank you for this. please create a PR. if you require additional help please let me know.

**Comment by robertosanval** [comment]
I need to know the data source to create a PR because all my implementations are based on Geonames data. Are we using the same data source?

**Comment by nnjeim** [comment]
I don't think so, please look in resources in the json files. could these files serve in your case?

**Comment by robertosanval** [comment]
I've seen it, but many populated places are missing in those files. At least in my country, that is what I know.
