### ISSUE TITLE
Possible to run database migrations on tenant?

### ISSUE THREAD

**Issue by DennisKraaijeveld** [nnjeim/world#27]
Hi! We do have a multitenancy app and I would like to run this package on the tenant. For this I will need to run migrations and seeders on the tenants but I do not see an option to config this. Possible solution or is this something which could be added?

**Comment by aeq-dev** [comment]
Check this : [Laravel-world](https://github.com/aeq-dev/laravel-world)

**Comment by nnjeim** [comment]
@DennisKraaijeveld Hi Dennis, Are you running different databases per tenant? in this case why don't you consider having a micro service providing the countries to all the tenants?
