### ISSUE TITLE
Some city strings are malformed

### ISSUE THREAD

**Issue by kabacs** [nnjeim/world#3]
While exploring your package I came across this anomaly - there is no space between words in data on the database tables.
All country, state, and city names are like this.

**Comment by nnjeim** [comment]
@kabacs Hi, can you please share some screenshots? thank you

**Comment by kabacs** [comment]
Hi, this is my code, in this case returning all cities from Portugal:

![Screenshot 2021-11-09 at 09 01 48](https://user-images.githubusercontent.com/1867010/140894385-c62d76ff-0f62-47b2-9f61-c84bebd3e86d.png)

The output from this request is then:

![Screenshot 2021-11-09 at 09 02 03](https://user-images.githubusercontent.com/1867010/140894457-22c7ee23-5dc7-44fa-bf06-3ef8f50f6352.png)

For example, the ID 90434, the name should be "Angra do Heroísmo", as with ID 90441, the name should be "Calheta de São Jorge", etc.

Also detected this with "United Kingdom", ex:

![Screenshot 2021-11-09 at 09 06 45](https://user-images.githubusercontent.com/1867010/140894967-c0ff50be-e143-423d-a7b7-accec164e0e2.png)

In this case, the output will be:

![Screenshot 2021-11-09 at 09 07 28](https://user-images.githubusercontent.com/1867010/140895032-c28cb442-8ea6-446d-9d01-c728a407aee2.png)

But if the string is together:

![Screenshot 2021-11-09 at 09 08 23](https://user-images.githubusercontent.com/1867010/140895177-a089fa19-35ac-41c9-9c81-93f2a187dfed.png)

The output then is:

![Screenshot 2021-11-09 at 09 08 56](https://user-images.githubusercontent.com/1867010/140895252-c4fe8087-81ed-43cc-a8ed-045181109dcb.png)

(Notice that the string in the names do not have spaces between them)

Thank you,
Ricardo Cabanelas

**Comment by nnjeim** [comment]
@kabacs Thank you for all the above. At first, the name of the country in the database is only used for filtering and in the return, the name is localized by taking into consideration the locale set in the HTTP header. I would filter by the iso field like:
``` 
'filters' => ['iso2' => 'FR']
```
Regarding the states and city names, the issue was fixed, i thank you for the patience you took to report this.
I am updating the version to 1.0.5

**Comment by kabacs** [comment]
@nnjeim thanks for the awesome package, plan on using it in production.
