### ISSUE TITLE
On-demand country name localization

### ISSUE THREAD

**Issue by OzanKurt** [nnjeim/world#31]
A good thing would be to make country names only available in english by default and make extras installable via a command `world:install-locale tr_TR` which will automatically pull the country data from `https://github.com/umpirsky/country-list/blob/master/data/tr_TR/country.php` and save it to the `lang/vendor` folder.

**Comment by nnjeim** [comment]
Hi, thanks a lot for your input. I have created a branch supporting the Turkish language for you to check.
There is 3 considerations of the locales support.
1- the locale should be part of the accepted_locales in the config file.
2- In the resources lang, a country.php file with the translated countries
3- Same is said for the response.php

https://github.com/nnjeim/world/tree/tr_locale_support

Let me know what do you think (i have translated the response.php using google translate) it might not be totally accurate.

All the best.

**Comment by nnjeim** [comment]
closed for lack of activity
