### ISSUE TITLE
Lang directory path changed 

### ISSUE THREAD

**Issue by a-j-n-a** [nnjeim/world#35]
when i run 
```  php artisan vendor:publish --tag=world ```
the lang directory goes under resources but after laravel 9 it should be in the root 
this make bug of all ```trans``` or ```__()``` not working unless i deleted ```resources/lang```

**Comment by nnjeim** [comment]
@a-j-n-a 
please try php artisan vendor:publish --tag=world --force

**Comment by a-j-n-a** [comment]
it still publishes it on resources, not in the lang directory 
![Screen Shot 2022-10-02 at 12 16 01 PM](https://user-images.githubusercontent.com/109465527/193449141-ae5dd0c3-ee88-468f-990c-4b2fc78bf1e7.png)

**Comment by nnjeim** [comment]
@a-j-n-a i will install the package on L9 and try this. I will let you know of my findings.

**Comment by nnjeim** [comment]
@a-j-n-a please try to look at translating as below:
trans('world:xxxx')
https://laravel.com/docs/9.x/packages#translations

**Comment by nnjeim** [comment]
closed by lack of activity.

**Comment by a-j-na** [comment]
Thanks a lot, man for this great effort
