### ISSUE TITLE
Migrations and seeding for devops pipeline

### ISSUE THREAD

**Issue by Jacq** [nnjeim/world#36]
**Is your feature request related to a problem? Please describe.**
I am integrating this package with a devops pipeline and an existing application. 
- The migrations are not published so I cannot change the order (modifying their timestamps) and they are applied after my migrations so I cannot add in my migrations the foreignId to the countries table as it is migrated later. 
- In my the devops pipeline I am migrating and seeding the database before running tests, and to speed up the tests I like to seed just some countries/cities/states.... and not the the full dataset. 

**Describe the solution you'd like**
I would like to change the migration order so this package is applied before my migrations, for that if possible it will be great if migrations are published so they timestamp can be modified, I do not know if this affects the package upgrades in the future.
It would be nice if the seed operation allows config option to allow partial or full seeding, so full can be perform just once and partial (much faster) can be used in testing for some records. 

**Describe alternatives you've considered**
I have checked that there is a migrations --package flag that could force the migration of a package but it only exists for newer laravel versions and I also prefer to keep the devops pipeline clean without code for this package.
Regarding the seeding for the testing, I have consider creating a custom countries/states... small seed so my tests start faster and still I have some data (not all) to check the relevant relations, but it will be more coherente to use the existing dataset instead of making up some new ones. 

**Additional context**
Thanks for this package :) !

**Comment by nnjeim** [comment]
@Jacq i appreciate the time it took you to write here. please feel free to contribute in suggesting some changes to make the package better. Please submit a PR i would do my best to help you if needed.
