### ISSUE TITLE
Seeder not adding any data

### ISSUE THREAD

**Issue by mohammad-azzam-dev** [nnjeim/world#43]
The seeder is nit adding any data

**Comment by nnjeim** [comment]
@mohammad-azzam-dev please make sure you publish the package assets before seeding.
```
composer require nnjeim/world

php artisan vendor:publish --tag=world

php artisan migrate

php artisan db:seed --class=WorldSeeder (requires ~15min)
```
if you are upgrading from an older version
please run
```
php artisan vendor:publish --tag=world
````
Let me know if this will work for you.

**Comment by mohammad-azzam-dev** [comment]
I did nothing happened and also tried all the steps you sent

**Comment by nnjeim** [comment]
> I did nothing happened and also tried all the steps you sent

@mohammad-azzam-dev 
Please check your laravel logs, do you see any errors?

**Comment by mohammad-azzam-dev** [comment]
nothing found

**Comment by nnjeim** [comment]
@mohammad-azzam-dev without errors in logs, i can't help to debug the issue. please try to run:
```
php artisan optimize:clear
```
then seed.
if this will not work too. i suggest you try on a freshly installed Laravel package.

**Comment by nnjeim** [comment]
@here closed by lack of activity

**Comment by mohammad-azzam-dev** [comment]
Hello, After digging deeper inside the vendor files and reading the code, then debugging each line we found out that we have to increase the memory size inside the apache server for php  (php.ini).
set the memory_limit to -1

before:
memory_limit = 128MB

after:
memory_limit = -1

Thank you for my fallow team mate Bilal for helping me find the problem Bilal Abo Jamous (https://github.com/Bilal-AJ0)

**Comment by nnjeim** [comment]
@mohammad-azzam-dev thank you for the update. All the best!
