### ISSUE TITLE
Include specific field in response

### ISSUE THREAD

**Issue by dpetrovaliev** [nnjeim/world#45]
Hey, i have the following scenario:
I should have a way to search cities by name and return the cities along with their country and state code:
Here is my action:
```
$action = World::cities([
            'fields' => 'country,state',
            'search' => $request->get('query')
        ]);
```   
As a result, I'm not receiving the state code but only the state id and state name. Is there any way to preload the states with the state_code?

**Comment by nnjeim** [comment]
@dpetrovaliev 
please look at the outcome here below
![Screenshot 2023-02-15 at 16 34 38](https://user-images.githubusercontent.com/78922079/219059146-77ed570c-7a2c-468a-9e00-4fee6a0ee3a1.jpg)
state code do not exist it is only state id and state name

**Comment by dpetrovaliev** [comment]
@nnjeim yes and the question was, how could I include it?

I think I found a solution:
- added the `state_code` in the optional fields in `world.php` config file and then recreated all the tables and then included `state_code` in fields when searching cities.

**Comment by nnjeim** [comment]
@dpetrovaliev excellent, thank you for your input
