### ISSUE TITLE
Remove states of Singapore

### ISSUE THREAD

**Issue by pengkong** [nnjeim/world#46]
Could I suggest that for the country of Singapore we **remove** this 5 states:

- Central Singapore Community Development Council
- North East Community Development Council
- North West Community Development Council
- South East Community Development Council
- South West Community Development Council

https://github.com/nnjeim/world/blob/master/resources/json/states.json#L39207

Reason: Singapore is tiny (smaller then New York City) and is itself a city-state. So strictly speaking Singapore has no states.

**Comment by nnjeim** [comment]
@pengkong 
It seems that the listed states are in reality regions or districts of the city itself.
https://en.wikipedia.org/wiki/Regions_of_Singapore
Please feel free to submit a PR removing the states.
Thank you for your contribution.
![Uploading Screenshot 2023-03-08 at 07.24.18.jpg…]()
