### ISSUE TITLE
languages.json has wrong language codes

### ISSUE THREAD

**Issue by svenraudkivi** [nnjeim/world#48]
**Describe the bug**
Czech and Croatian language codes are wrong in the file resources/json/languages.json.

**Additional context**
Czech code should be "cs" and Croatian code should be "hr" as listed in https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes.

**Comment by nnjeim** [comment]
@svenraudkivi I thank you for this correction. Please pull the corrected version v1.1.22
