### ISSUE TITLE
set Header accept-language=locale does not work

### ISSUE THREAD

**Issue by know-that** [nnjeim/world#5]
![image](https://user-images.githubusercontent.com/31246220/141402028-ba8bb713-b582-4f72-b7f1-a2184d2e7109.png)

**Comment by know-that** [comment]
My interface must use `\Nnjeim\World\Http\Middleware\Localization::class`

**Comment by nnjeim** [comment]
@know-that The package world is using it's own middleware Nnjeim\World\Http\Middleware\Localiztion
I am sharing with you the result of postman requests.
1- the locale should be set in the header.
2- Only the countries list is localized. if you know of a source of localized cities please share.
3- If you need to use your own middleware for localization you might consider forking the package and modifying this part.

At last i thank you for your input and looking forward for your contribution.
![Screenshot 2021-11-12 at 05 55 28](https://user-images.githubusercontent.com/78922079/141406963-9084aab6-a64e-4d9b-985a-1006e10e8ece.jpg)
![Screenshot 2021-11-12 at 05 54 52](https://user-images.githubusercontent.com/78922079/141406978-b71bf181-c4ff-41e7-8845-cfca02eaf303.jpg)
