### ISSUE TITLE
Seed create multiple same currency

### ISSUE THREAD

**Issue by jaguar19961** [nnjeim/world#50]
**Describe the bug**
Then seed the DB in the currency table creating multiple of the same currency.

**To Reproduce**
1. php artisan db:seed --class=WorldSeeder

**Screenshots**
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/38075360/228185889-8573a3ac-41de-4c80-8fc0-132ba37c5343.png">

**Comment by nnjeim** [comment]
Can you please validate if different countries are using the same currency I can see in your table that the country id differsSent from my iPhoneOn 28 Mar 2023, at 12:13, jaguar19961 ***@***.***> wrote:﻿
Closed #50 as completed.
