### ISSUE TITLE
Think about add limit parameter to your API points

### ISSUE THREAD

**Issue by EntroSolutions** [nnjeim/world#51]
Think about adding limit parameter to your API points or maybe I cant find how to add limit?

**Comment by nnjeim** [comment]
@EntroSolutions 

Hi are you referring to the rate limit?

Please check the routes file

```
Route::group([
	'prefix' => '{prefix?}',
	'middleware' => [
		'throttle:60,1',
		Localization::class,
	],
], function () {
```

**Comment by nnjeim** [comment]
closed by lack of activity
