### ISSUE TITLE
Missing country language entry for XK (Kosovo)

### ISSUE THREAD

**Issue by verstratenbram** [nnjeim/world#52]
**Describe the bug**
When fetching the country with iso2 `XK` we get a missing name:
```
[
    "id" => 116,
    "iso2" => "XK",
    "name" => "world::country.XK",
]
```
**To Reproduce**
1. call: 
```
World::countries( [ 
  "fields" => "iso2,name"
  "filters" => [
    "iso2" => "XK"
  ]
]);
```
2. See the missing county name in the result.

**Expected behavior**
When fetching the country with iso2 XK we should get:
```
[
    "id" => 116,
    "iso2" => "XK",
    "name" => "Kosovo",
]
```

**Comment by nnjeim** [comment]
@verstratenbram 
Thank you for this. I have added the localisation of the name of the country Kosovo. Please consider pulling 1.1.24
