### ISSUE TITLE
Seeder error: Column 'native' cannot be null

### ISSUE THREAD

**Issue by WIDESRL** [nnjeim/world#56]
The database seeder returns a critical error on `native` column for table `countries`.

To reproduce is enough to set as required the `native` field  under migrations block in the configuration file (migrations->countries->optional_fields->nativa) and then run the seeder with artisan command `php artisan world:refresh`

This is the error it gives:
`Integrity constraint violation: 1048 Column 'native' cannot be null (Connection: mysql, SQL: insert into `countries` (`name`, `iso3`, `iso2`, `phone_code`, `native`, `region`, `subregion`) values (Cote D'Ivoire (Ivory Coast), CIV, CI, 225, ?, Africa, Western Africa))`

**Comment by nnjeim** [comment]
@WIDESRL Thank you for reporting this issue. The missing Côte d'Ivoire native name was added in the countries json source file. you can upgrade to v 1.1.26
