### ISSUE TITLE
I hope to add language packs for cities and streets in the future

### ISSUE THREAD

**Issue by know-that** [nnjeim/world#6]
I hope to add language packs for cities and streets in the future

**Comment by nnjeim** [comment]
@know-that Hi. can you please share a source of the localised name for cities?

**Comment by know-that** [comment]
> @知道-你好。你能分享一下城市本地化名称的来源吗？

it's my honour, give me some time.

**Comment by know-that** [comment]
> @know-that Hi. can you please share a source of the localised name for cities?

China area: [https://github.com/eduosi/district/blob/master/district-standard.csv](https://github.com/eduosi/district/blob/master/district-standard.csv)
