### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes)

### ISSUE THREAD

**Issue by hafizSiddiq7675** [nnjeim/world#60]
When trying to seed the database, it is causing error like Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes)

**Comment by nnjeim** [comment]
@hafizSiddiq7675 please try to increase the memory in php.ini

**Comment by VictorBassey-web** [comment]
I increased mine to memory_limit = 1024M but it still doesn’t work 
Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)

Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in vendor/nnjeim/world/src/Actions/SeedAction.php on line 119

**Comment by ahmadyousefdev** [comment]
@nnjeim 
Just a suggestion,
Can you chunk the seeding process, this way it might work without the need to increase the memory_limit
converting the seeding file into multiple files can make it work too..
