### ISSUE TITLE
Missing Main Italian Provinces

### ISSUE THREAD

**Issue by 0chak** [nnjeim/world#62]
**Is your feature request related to a problem? Please describe.**
There are some Italian provinces missing: its major cities like Rome, Naples, Milan, Turin and more (which are metropolitan cities and also provinces at the same time)

**Describe the solution you'd like**
I wanted to add them to the states json but then I thought: should I add the native name "Napoli" or english "Naples" or both

I think we should add the native name field also to cities and states, like you did in `countries` because for example I found both Naples and Napoli in `cities` which is referred to the same city and it doesn't have sense when you load the whole list in a select menu

**Comment by nnjeim** [comment]
@0chak
thank you for your input. 
what are looking for could be listed under cities. (check Napoli and Roma in cities)

in states.json file you can add the missing states as below
  {
        "id": 1681,
        "name": "Ascoli Piceno",
        "country_id": 107,
        "country_code": "IT",
        "country_name": "Italy",
        "state_code": "AP",
        "type": "province",
        "latitude": "42.86389330",
        "longitude": "13.58997330"
    },
    
    you need to attribute an incremental ID for the object.
    the name should be in italian
         "country_id": 107,
        "country_code": "IT",
        "country_name": "Italy",
        the below properties should be added
        "state_code": ?,
        "type": "province",
        "latitude": ?,
        "longitude": ?
