### ISSUE TITLE
Adding additional cities/states to cities.json and states.json

### ISSUE THREAD

**Issue by clarkripm** [nnjeim/world#65]
Cannot edit cities.json or states.json or reupload files on my fork and submit a pull request due to the size of both files. Our org is using this package for a project and need to add a few cities/states that are in our db seem to be missing from cities.json:

Singapore*, Asunción*, İstanbul, Arendal, St. Gallen, Chambost-Allières, Ceuta*, Fort-de-France

* these cities are city/states that are also missing from states.json

See the suggested additions below, without ids/codes where applicable:

cities.json:
`    {
        "id": null, //needs to be generated
        "name": "Singapore",
        "state_id": null, //needs to be generated after state created
        "state_code": "null", //needs to be generated after state created
        "state_name": "Singapore",
        "country_id": 199,
        "country_code": "SG",
        "country_name": "Singapore",
        "latitude": "1.283333",
        "longitude": "103.833333,
        "wikiDataId": "Q334"
    },
    {
        "id": null, //needs to be generated
        "name": "Asunción",
        "state_id": null, //needs to be generated after state created
        "state_code": "null", //needs to be generated after state created
        "state_name": "Singapore",
        "country_id": 172,
        "country_code": "PY",
        "country_name": "Paraguay",
        "latitude": "-25.3",
        "longitude": "-57.633333",
        "wikiDataId": "Q2933"
    },
    {
        "id": null, //needs to be generated
        "name": "İstanbul",
        "state_id": 2170,
        "state_code": "34",
        "state_name": "İstanbul",
        "country_id": 225,
        "country_code": "TR",
        "country_name": "Turkey",
        "latitude": "41.16343020",
        "longitude": "28.76644080",
        "wikiDataId": "Q406"
    },
    {
        "id": null, //needs to be generated
        "name": "Arendal",
        "state_id": 1014,
        "state_code": "42",
        "state_name": "Agder",
        "country_id": 165,
        "country_code": "NO",
        "country_name": "Norway",
        "latitude": "58.4612",
        "longitude": "8.7669",
        "wikiDataId": "Q2699921"
    },
    {
        "id": null, //needs to be generated
        "name": "St. Gallen",
        "state_id": 1644,
        "state_code": "SG",
        "state_name": "St. Gallen",
        "country_id": 214,
        "country_code": "CH",
        "country_name": "Switzerland",
        "latitude": "47.424167",
        "longitude": "9.370833",
        "wikiDataId": "Q25607"
    },
    {
        "id": null, //needs to be generated
        "name": "Chambost-Allières",
        "state_id": 5037,
        "state_code": "69",
        "state_name": "Rhône",
        "country_id": 75,
        "country_code": "FR",
        "country_name": "France",
        "latitude": "46.0192",
        "longitude": "4.4992"
        "wikiDataId": "Q2026"
    },
    {
        "id": null, //needs to be generated
        "name": "Ceuta",
        "state_id": null, //needs to be generated after state created
        "state_code": "null", //needs to be generated after state created
        "state_name": "Ceuta",
        "country_id": 207,
        "country_code": "ES",
        "country_name": "Spain",
        "latitude": "35.888333",
        "longitude": "-5.315556",
        "wikiDataId": "Q5823"
    },
    {
        "id": null, //needs to be generated
        "name": "Fort-de-France",
        "state_id": 4827, 
        "state_code": "972", 
        "state_name": "Martinique",
        "country_id": 75,
        "country_code": "FR",
        "country_name": "France",
        "latitude": "14.6,
        "longitude": "-61.066667",
        "wikiDataId": "Q81621"
    },`

states.json
`    {
        "id": null, //needs to be generated
        "name": "Singapore",
        "country_id": 199,
        "country_code": "SG",
        "country_name": "Singapore",
        "state_code": "01",
        "type": null,
        "latitude": "1.283333",
        "longitude": "103.833333"
    },
    {
        "id": null, //needs to be generated
        "name": "Asunción",
        "country_id": 172,
        "country_code": "PY",
        "country_name": "Paraguay",
        "state_code": "null", //needs to be generated after state created
        "type": null,
        "latitude": "-25.3"",
        "longitude": "-57.633333"
    },
    {
        "id": null, //needs to be generated
        "name": "Ceuta",
        "country_id": 207,
        "country_code": "ES",
        "country_name": "Spain",
        "state_code": "null", //needs to be generated after state created
        "type": null,
        "latitude": "35.888333",
        "longitude": "-5.315556",
    },`

**Comment by nnjeim** [comment]
@clarkripm on your fork you should be able to edit anything and re-upload it. can you share with me the error you are getting?

**Comment by clarkripm** [comment]
<img width="1108" alt="Screenshot 2023-10-30 at 2 30 14 PM" src="https://github.com/nnjeim/world/assets/95714424/5dd785e9-681f-4c9b-b1ca-15787a3af342">
<img width="499" alt="Screenshot 2023-10-30 at 2 30 44 PM" src="https://github.com/nnjeim/world/assets/95714424/7cdddf33-8cf8-4088-91db-21c0ffcc2fb0">

Getting these file size errors on my own fork, but I'm using github itself. I didn't want to clone the repo so I haven't tried to push the changes from my machine, but if I need to for large file edits then I will

**Comment by nnjeim** [comment]
@clarkripm did you try to submit a PR and merge? try a git command from the console.
