### ISSUE TITLE
Missing support for languages like is Serbian that have default cyrillic and latin versions

### ISSUE THREAD

**Issue by stefanrakicfaxi** [nnjeim/world#69]
**Describe the bug**
I tried to add a custom language Serbian Latin and the code for that is sr_Latn, now that is not supported but I think it can be easily done in WorldServiceProvider. A temporary solution is to use sr but that is not good solution because in the future I should have a Serbian Cyrillic version

**Comment by nnjeim** [comment]
@stefanrakicfaxi thank you for your input, can you contribute in adding this locale to the repo?
the local should be added in the config file, then the translation of the countries native names should be added in the resources.

**Comment by stefanrakicfaxi** [comment]
Yes, of course, I will create PR
