### ISSUE TITLE
As suggestion, add Airports Information

### ISSUE THREAD

**Issue by claytongf** [nnjeim/world#7]
Hi,

As a huge enhancement, is it possible to add airports information with IATA code, etc,  and link them to the cities in a future release?

**Comment by nnjeim** [comment]
@claytongf Hi there, thank you for this suggestion. I will research this asap. If you have access to some resources please share.

**Comment by claytongf** [comment]
Hi!
I've found a package which contains a json file with airports information. I don't know if the information is fully accurate. But, I think it may help

[https://github.com/mwgg/Airports](url)
