### ISSUE TITLE
Missing Italian states

### ISSUE THREAD

**Issue by WIDESRL** [nnjeim/world#70]
hi, 

this library is very convenient and I'm using it a lot. However, I noticed that some are missing from the list of Italian provinces (states). Can I prepare a list of the missing ones or would you prefer a pull request?

**Comment by nnjeim** [comment]
@WIDESRL the translation to italian is being handled by the PR
https://github.com/nnjeim/world/pull/66
We are looking to extend the translation of the states to all the supported languages.
If what you need is urgent you can fork the repo and copy the content of the PR.

**Comment by nnjeim** [comment]
> if you are already working on the translations I can wait. but my report is for missing states not for translations

Hi again, it might take some time, if you are in a hurry please fork the repository, add your missing states by respecting the following data structure.

```
 {
        "id": 1688,
        "name": "Apulia",
        "country_id": 107,
        "country_code": "IT",
        "country_name": "Italy",
        "state_code": "75",
        "type": "region",
        "latitude": "40.79283930",
        "longitude": "17.10119310"
    },
    
    ```

then you can run 'php artisan world:refresh' to reseed your database.
