### ISSUE TITLE
Translation for states

### ISSUE THREAD

**Issue by zackAJ** [nnjeim/world#73]
Hello, is there a possibility to add translation keys to states?

**Comment by nnjeim** [comment]
@zackAJ Hi yes it is possible, however we are exploring on the source of the translated files. If you have access to such a source, please share.

**Comment by zackAJ** [comment]
@nnjeim I'm working on a project currently that will eventually have the states translated, I can provide Algeria's (id=4) states in French and Arabic for now.

**Comment by nnjeim** [comment]
@zackAJ thank you for your input, but i am looking for a complete solution covering all countries.
