### ISSUE TITLE
Timezones in Country table for Country AU are for Daylight savings time, not standard.

### ISSUE THREAD

**Issue by TheITJuggler** [nnjeim/world#85]
**Describe the bug**
For the Australian states that follow daylight savings time, the UTC offset and the Time zone name reflect only the Dayligh Savings zone details.

**To Reproduce**
Go to World/resources/json/countries.json
Find zonename Australia\/Sydney
See that GMTOffset and GMTOffsetName are off by an hour
See that TZName contains "Daylight" and not "Standard"

**Expected behavior**
Additional column indicating if timezone follows daylight savings
Additional column indicating daylight savings incremement (default 3600)
Additional column indicating daylight savings TZname (i.e AEST becomes AEDT in daylight savings)
Possibly include tzdata 

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/a

**Additional context**

**Comment by nnjeim** [comment]
@TheITJuggler Thank you for your input, if i remember right the timezones in the countries.json were used only to seed the table timezones. Multiple timezones should be available for Australia.
The purpose of this is to allow a user to select his current timezone but no timezone translation is offered by the package.
Check the table timezones pls and let me know if more information could be added there.

**Comment by nnjeim** [comment]
closed by lack of input
