### ISSUE TITLE
Country translations not working

### ISSUE THREAD

**Issue by Faridleo1998** [nnjeim/world#87]
**Describe the bug**
I published the package config, I moved the translations (/resources/lang/vendor/world/*) to /lang folder in root project, but translations not loading.

I moved folder because I use filament php and shield packages and this package create /lang folder.

My .env file has APP_LOCALE=es

**To Reproduce**
1. Execute php artisan vendor:publish --tag=world --force.
2. Move /resources/lang/vendor/world to /lang in root project. result path: /lang/vendor/world/*

![image](https://github.com/nnjeim/world/assets/57077376/05868c2b-6b4e-4e3c-b9b9-d2a7f914b63f)

![image](https://github.com/nnjeim/world/assets/57077376/9f2b5579-f734-48dd-b5bf-989d5ebb26fe)

**Comment by nnjeim** [comment]
@Faridleo1998 hi and thank you for your input. My understanding is that the .env props are undefined in production and you should try to programatically set the locale using the config helper.

please check the code where the country translations is done and it will be clearer.

**Comment by Faridleo1998** [comment]
My project is local environment and it has .env file with language configuration but the countries names not show in spanish.

**Comment by nnjeim** [comment]
to set the locale you need to programatically set it not only .env
try in a middleware to add 
app()->setLocale('es');

will this work

look at this part of the code in the package

<?php

namespace Nnjeim\World\Http\Middleware;

use Illuminate\Http\Request;
use Closure;

class Localization
{
	/**
	 * @param  Request  $request
	 * @param  Closure  $next
	 * @return mixed
	 */
	public function handle(Request $request, Closure $next): mixed
	{
		$requestLocale = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'] ?? config('app.fallback_locale'), 0, 2);

		$setLocale = in_array($requestLocale, config('world.accepted_locales'), true)
			? $requestLocale
			: config('app.fallback_locale');

		app()->setLocale($setLocale);

		return $next($request);
	}
}

**Comment by Faridleo1998** [comment]
How I use the setLocale function in filament php?

**Comment by nnjeim** [comment]
> How I use the setLocale function in filament php?

i guess you call the facade of the world package and then call the World::setLocale('localeString')->countries()

**Comment by nnjeim** [comment]
> I trying use the facade but not working, I put in a service provider in boot method.

Please refer to the Readme file it shows an example how the facade is used.
