### ISSUE TITLE
https://laravel-world.com has no Frontend?

### ISSUE THREAD

**Issue by sluxzer** [nnjeim/world#95]
Hi, Author

This is great package

If I'm not mistaken the current domain purpose only for API?
it would be good if we add some UI to show the Data

I would love to help creating the UI, what do you think?

also, I like to know where the source truth from this coutry and city seeder, and perhaps is there any step to update the seeder in proper way

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/80b7ced1-64df-4df1-86b5-d8314b799b51">

**Comment by sluxzer** [comment]
We could use reactjs and tailwindcss for this, or even better with NextJS

what do you think?

**Comment by nnjeim** [comment]
@sluxzer i think your idea of using react and tailwind is perfect however please access the stack below:

React + PrimeReact + Primeflex
https://primereact.org/
https://primeflex.org/

Let me know what do you think?

**Comment by sluxzer** [comment]
I'll looking it to it.

anyway, this feature will great for https://hacktoberfest.com/
