### ISSUE TITLE
seed run bug

### ISSUE THREAD

**Issue by bahramzade** [nnjeim/world#97]
**Describe the bug**

**To Reproduce**
after seed run

**Expected behavior**

**Screenshots**

<img width="642" alt="Screenshot 2024-10-21 at 13 31 29" src="https://github.com/user-attachments/assets/4fe973de-4dfb-4d5c-a4de-a5d304187a15">
and database not inserted

**Additional context**

**Comment by nnjeim** [comment]
@bahramzade can you please try the install helper?
php artisan world:install

**Comment by nnjeim** [comment]
@bahramzade please share the error you are getting. did you verify your connection to the database?

**Comment by vygandas** [comment]
Same issue here. On windows, seeder was running, but db tables are empty (PostgreSQL). On mac, seeder starts and stops in a moment and nothing happens at all (SQLite).

**Comment by fabyo0** [comment]
@vygandas Yes, I use a Mac and I have the same problem.

**Comment by vygandas** [comment]
@fabyo0 check this out https://github.com/nnjeim/world/issues/53#issuecomment-2454484506 ✌️

**Comment by fabyo0** [comment]
> @fabyo0 check this out [#53 (comment)](https://github.com/nnjeim/world/issues/53#issuecomment-2454484506) ✌️

Thanks 👍

**Comment by bahramzade** [comment]
> @fabyo0 check this out [#53 (comment)](https://github.com/nnjeim/world/issues/53#issuecomment-2454484506) ✌️

php -d memory_limit=1G artisan db:seed --class=WorldSeeder

**Comment by socrec** [comment]
> > @fabyo0 check this out [#53 (comment)](https://github.com/nnjeim/world/issues/53#issuecomment-2454484506) ✌️
> 
> php -d memory_limit=1G artisan db:seed --class=WorldSeeder

This should totally be in the official document. Because it's still happening all the time

**Comment by nnjeim** [comment]
@socrec we will add this in the readme asap. Thank you for your input.
