### ISSUE TITLE
cannot publish tables

### ISSUE THREAD

**Issue by henry-ht** [nnjeim/world#98]
The tables cannot be published in the project to relate the data, it is not possible to set a date for the migration file names.

**Comment by nnjeim** [comment]
@henry-ht can you please share more details? the error you are getting and which version of laravel you are using?
Are you upgrading for an earlier version? or is it a fresh install?
try follow these steps
```
php artisan vendor:publish --tag=world

php artisan migrate

php artisan db:seed --class=WorldSeeder

**Comment by henry-ht** [comment]
> @henry-ht can you please share more details? the error you are getting and which version of laravel you are using? Are you upgrading for an earlier version? or is it a fresh install? try follow these steps
> 
> ```
> php artisan vendor:publish --tag=world
> 
> php artisan migrate
> 
> php artisan db:seed --class=WorldSeeder
> ```

more than an error, it is a problem to be able to add it to an existing project. for example, as the tables are always created at the end, it is impossible for me to establish a relationship with the user table

**Comment by nnjeim** [comment]
@henry-ht i don't fully understand the problem but for custom implementation i would suggest you clone the repository, and many copy and adapt the code in order for you to create a relationship with users which is not supported by the package itself
